apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: post 
  serviceName: "postgres-svc"
  replicas: 3 
  template:
    metadata:
      labels:
        app: post 
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage-new
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_DB
          value: "coordinates_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"

  volumeClaimTemplates:
  - metadata:
      name: postgres-storage-new
      labels:
        app: post
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "1Gi"

