apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: post
spec:
  ports:
  - port: 5432
  type: ClusterIP # it is ClusterIP by default but you said to write it
  clusterIP: None
  selector:
    app: post